describe("toolchain", function()
  it("loads dkjson with null sentinel", function()
    local json = require("dkjson")
    assert.is_not_nil(json.null)
    local d = json.decode("[1,null,2]", 1, json.null)
    assert.equal(3, #d)
  end)
end)

describe("rockspec", function()
  it("lists every module under src", function()
    local f = assert(io.popen("ls rocksmcp-*.rockspec"))
    local path = f:read("*l")
    f:close()
    local spec = assert(io.open(path)):read("*a")
    local p = assert(io.popen("find src -name '*.lua'"))
    for file in p:lines() do
      assert.truthy(spec:find('"' .. file .. '"', 1, true), file .. " missing from " .. path)
    end
    p:close()
  end)
end)
