local S = require("rocksmcp.schema")
local json = require("rocksmcp.json")

describe("schema", function()
  it("builds object schemas with required arrays", function()
    local sch = S.obj({ who = S.str("Name") }, { "who" }, "Args")
    assert.equal("object", sch.type)
    assert.equal("Args", sch.description)
    assert.same({ "who" }, sch.required)
    assert.equal("string", sch.properties.who.type)
  end)

  it("omits empty required and encodes properties as object", function()
    local sch = S.obj({}, {})
    assert.is_nil(sch.required)
    assert.equal("object", sch.type)
    assert.equal("{}", json.encode(sch.properties):gsub("%s", ""))
  end)

  it("supports opts on primitives", function()
    local n = S.num("Count", { min = 1, max = 10, default = 5 })
    assert.equal(1, n.minimum)
    assert.equal(10, n.maximum)
    assert.equal(5, n.default)
    local i = S.int("Index")
    assert.equal("integer", i.type)
    local s = S.str("Id", { pattern = "^%w+$" })
    assert.equal("^%w+$", s.pattern)
  end)

  it("builds arrays and enums", function()
    local a = S.arr(S.str(), "List")
    assert.equal("array", a.type)
    assert.equal("string", a.items.type)
    local e = S.enum({ "x", "y" }, "Choice")
    assert.same({ "x", "y" }, e.enum)
  end)

  it("does not mutate caller tables", function()
    local props = { who = S.str("Name") }
    local req = { "who" }
    local vals = { "x", "y" }
    S.obj(props, req)
    S.enum(vals)
    assert.is_nil(getmetatable(props))
    assert.is_nil(getmetatable(req))
    assert.is_nil(getmetatable(vals))
  end)

  describe("map, any, nullable", function()
    it("builds them", function()
      assert.same({ type = "object", additionalProperties = { type = "integer" }, description = "M" },
        S.map(S.int(), "M"))
      assert.same({ description = "A" }, S.any("A"))
      local n = S.nullable(S.str("x"))
      assert.same({ "string", "null" }, n.type)
      assert.equal("x", n.description)
      local raw = S.nullable(S.any())
      assert.is_nil(raw.type)
    end)

    it("validates them", function()
      assert.is_true(S.validate(S.nullable(S.str()), json.null()))
      assert.is_true(S.validate(S.any(), function() end))
      local ok, errs = S.validate(S.map(S.int()), { a = 1, b = "x" })
      assert.is_false(ok)
      assert.same({ "arguments.b must be integer, got string" }, errs)
    end)
  end)

  describe("validate", function()
    it("checks lengths in characters and item counts on plain tables", function()
      local sch = S.obj({
        s = S.str(nil, { min_length = 2, max_length = 3 }),
        l = S.arr(S.int(), nil, { min_items = 1, max_items = 2 }),
      })
      assert.is_true(S.validate(sch, { s = "\195\169\195\169", l = { 1 } }))
      local _, errs = S.validate(sch, { s = "a", l = { 1, 2, 3 } })
      assert.same({ "arguments.l must have at most 2 items", "arguments.s must be at least 2 characters" }, errs)
      _, errs = S.validate(sch, { s = "abcd", l = json.array({}) })
      assert.same({ "arguments.l must have at least 1 items", "arguments.s must be at most 3 characters (got 4)" }, errs)
    end)

    it("reports a type for odd Lua values", function()
      local _, errs = S.validate(S.str(), print, "x")
      assert.same({ "x must be string, got function" }, errs)
    end)
  end)
end)
