local S = require("rocksmcp.schema")
local json = require("rocksmcp.json")

describe("schema", function()
  it("builds object schemas with required arrays", function()
    local sch = S.obj({ who = S.str("Name") }, { "who" }, "Args")
    assert.equal("object", sch.type)
    assert.equal("Args", sch.description)
    assert.same({ "who" }, sch.required)
    assert.equal("string", sch.properties.who.type)
  end)

  it("omits empty required and encodes properties as object", function()
    local sch = S.obj({}, {})
    assert.is_nil(sch.required)
    assert.equal("object", sch.type)
    assert.equal("{}", json.encode(sch.properties):gsub("%s", ""))
  end)

  it("supports opts on primitives", function()
    local n = S.num("Count", { min = 1, max = 10, default = 5 })
    assert.equal(1, n.minimum)
    assert.equal(10, n.maximum)
    assert.equal(5, n.default)
    local i = S.int("Index")
    assert.equal("integer", i.type)
    local s = S.str("Id", { pattern = "^%w+$" })
    assert.equal("^%w+$", s.pattern)
  end)

  it("builds arrays and enums", function()
    local a = S.arr(S.str(), "List")
    assert.equal("array", a.type)
    assert.equal("string", a.items.type)
    local e = S.enum({ "x", "y" }, "Choice")
    assert.same({ "x", "y" }, e.enum)
  end)

  it("does not mutate caller tables", function()
    local props = { who = S.str("Name") }
    local req = { "who" }
    local vals = { "x", "y" }
    S.obj(props, req)
    S.enum(vals)
    assert.is_nil(getmetatable(props))
    assert.is_nil(getmetatable(req))
    assert.is_nil(getmetatable(vals))
  end)
end)
